---
title: '2021-05-24'
author: "Yuwei Cheng"
date: "2021/5/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries
library(stringr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(scales)
```

```{r}
# Function cell

# Split different types of contract
splitCon = function(x,name)
{
  x %>% subset(contract_type %in% c(name)) %>% 
    select(close, trade_time, symbol)
}

selectSWAP = function(x,y)
{
  x %>% subset(contract_type %in% c("SWAP")) %>% 
    select(close, trade_time, symbol) %>%
    subset(trade_time %in% y$trade_time)
}

makedf = function(x,y)
{
  df = merge(x,y,by = "trade_time") %>%
    # rename("curweek" = "close.x") %>%
    # rename("swap" = "close.y") %>%
    mutate(diff = close.x - close.y) %>%
    mutate(return = (close.x - close.y)/close.y)
  return(df)
}

returnDist = function(x, t1, t2)
{
  print(signif(summary(x$return[x$trade_time<t1]), 3))
  print(signif(summary(x$return[x$trade_time>t1 & x$trade_time<t2]), 3))
  print(signif(summary(x$return[x$trade_time>t2]), 3))
}

returnPlot = function(x,t1,t2)
{
  par(mfrow = c(1,3), mar = c(3,3,1,1))
  hist(x$return[x$trade_time<t1], xlab = "", ylab = "return", main = NULL)
  hist(x$return[x$trade_time>t1 & x$trade_time<t2],
        xlab = "", ylab = "return",  main = NULL)
  hist(x$return[x$trade_time>t2],  xlab = "", ylab = "return",  main = NULL)
  par(mfrow = c(1,1))
}

```

```{r}
data = read.csv("C:/Users/yuwei/Documents/GitHub/tradeAnalysis/data/BTC/btc_usdt_60min_all.csv")

# Exchange platform: OKEX
# TS_code: BTC_USDT
# Freq: on hour, 60 minutes
# Is_contract: Yes

data = data %>% 
  select(-X, - exchange, - ts_code, -freq, -is_contract) %>%
  mutate(trade_time = ymd_hm(trade_time))

data$contract_type = 
  do.call(rbind,
          str_split(data$symbol, "-", n = Inf, simplify = FALSE))[,3]

# Label contract type
data = data %>% 
  mutate(contract_type =  
           ifelse(contract_type != "SWAP",
                  contract_type, "180101")) %>% 
  mutate(type = ymd(contract_type)) %>%
  mutate(date = as.Date(trade_time)) %>%
  mutate(difference = type - date) %>%
  mutate(contract_type  = 
           ifelse(difference <0, "SWAP",
                  ifelse(difference >= 90, "4 Next Season",
                         ifelse(difference >=14, "3 Current Season",
                                ifelse(difference >= 7, "2 Next Week",
                                       "1 Current Week")))))%>%
  select(-difference, -date, -type)

```

```{r}
current_week  = splitCon(data, "1 Current Week")
next_week = splitCon(data, "2 Next Week")
current_season = splitCon(data, "3 Current Season")
next_season = splitCon(data, "4 Next Season")



swap = selectSWAP(data, current_week)
current_week = current_week %>% subset(trade_time %in% swap$trade_time)
df1 = makedf(current_week, swap)

swap = selectSWAP(data, next_week)
next_week = next_week %>% subset(trade_time %in% swap$trade_time)
df2 = makedf(next_week, swap)

swap = selectSWAP(data, current_season)
current_season = current_season %>% subset(trade_time %in% swap$trade_time)
df3 = makedf(current_season, swap)

swap = selectSWAP(data, next_season)
next_season = next_season %>% subset(trade_time %in% swap$trade_time)
df4 = makedf(next_season, swap)
```

```{r}
df1 %>% ggplot() +
  geom_line(aes(x = trade_time, y = return)) + theme_bw() +
  geom_vline(xintercept = df1$trade_time[c(820, 8019)],
             linetype = "dotted",
             color = "red")+
  scale_x_datetime(breaks = date_breaks("2 month"),
                   minor_breaks = date_breaks("7 day"))+
  labs(x = NULL, title = "当周合约和永续合约")
```

```{r}
returnDist(df1, df1$trade_time[820], df1$trade_time[8019])
```

```{r}
returnPlot(df1, df1$trade_time[820], df1$trade_time[8019])
```


```{r}
df2 %>% ggplot() +
  geom_line(aes(x = trade_time, y = return)) + theme_bw() +
  geom_vline(xintercept = df1$trade_time[c(820,8019)],
             linetype = "dotted",
             color = "red")+
  scale_x_datetime(breaks = date_breaks("2 month"),
                   minor_breaks = date_breaks("14 day"))+
  labs(x = NULL, title = "次周合约和永续合约")
```

```{r}
returnDist(df2, df1$trade_time[820], df1$trade_time[8019])
returnPlot(df2, df1$trade_time[820], df1$trade_time[8019])
```


```{r}
df3 %>% ggplot() +
  geom_line(aes(x = trade_time, y = return)) + theme_bw() +
  geom_vline(xintercept = df1$trade_time[c(820,8019)],
             linetype = "dotted",
             color = "red")+
  scale_x_datetime(breaks = date_breaks("2 month"),
                   minor_breaks = date_breaks("1 month")) +
  labs(x = NULL, title = "当季合约和永续合约")
```

```{r}
returnDist(df3, df1$trade_time[820], df1$trade_time[8019])
returnPlot(df3, df1$trade_time[820], df1$trade_time[8019])
```


```{r}
df4 %>% ggplot() +
  geom_line(aes(x = trade_time, y = return)) + theme_bw() +
  geom_vline(xintercept = df1$trade_time[c(820, 8019)],
             linetype = "dotted",
             color = "red")+
  scale_x_datetime(breaks = date_breaks("2 month"),
                   minor_breaks = date_breaks("1 month")) +
  labs(x = NULL, title = "次季合约和永续合约")
```


```{r}
returnDist(df4, df1$trade_time[820], df1$trade_time[8019])
returnPlot(df4, df1$trade_time[820], df1$trade_time[8019])
```

```{r}
# data = read.csv("C:/Users/yuwei/TG RESEARCH Dropbox/历史数据/priceAnalysis/data/BTC/btc_usdt_60min_all.csv")
# data = data %>% select(-X, - exchange, - ts_code, -freq, -is_contract) %>%
#   mutate(trade_time = ymd_hms(trade_time))

# data$contract_type = do.call(rbind,
#         str_split(data$symbol, "-", n = Inf, simplify = FALSE))[,3]
# 
# # Classify contract type
# data =
# data %>% mutate(contract_type =  ifelse(contract_type != "SWAP",
#                                         contract_type, "180101")) %>%
#   mutate(type = ymd(contract_type)) %>%
#   mutate(date = as.Date(trade_time)) %>%
#   mutate(difference = type - date) %>%
#   mutate(contract_type  =
#            ifelse(difference <0, "SWAP",
#                   ifelse(difference >= 90, "4 Next Season",
#                          ifelse(difference >=14, "3 Current Season",
#                                 ifelse(difference >= 7, "2 Next Week",
#                                        "1 Current Week")))))%>%
#   select(-difference, -date, -type)

# Price
data %>%
  ggplot() +
  geom_line(aes(x = trade_time, y=close, colour = contract_type)) +
  theme_bw() + labs(x = "Trade Time", y = "BTC Close Price",
                    colour = "Type")+
  scale_x_datetime(date_labels = "%b-%d", breaks = "2 month") +
  scale_y_continuous(breaks = seq(10000, 80000, 10000)) +
  # scale_color_viridis(discrete = TRUE, option = "D")
  scale_color_manual(values=c("#999999", "#E69F00",
                              "#56B4E9", "#d62828", "#003566"))
# Volume
data %>%
  ggplot() + facet_wrap(~ contract_type) +
  geom_line(aes(x = trade_time, y = log(vol)),color = "steelblue") +
  theme_bw() + labs(x = "Trade Time", y = "BTC vol in log scale",
                    colour = "Type")+
  scale_x_datetime(date_labels = "%b-%d", breaks = "2 month")

```

```{r}
# Identify days which has extremely low volume
data %>% subset(contract_type == "SWAP") %>%
  subset(vol == min(vol))

data %>% subset(contract_type == "1 Current Week") %>%
  subset(vol == min(vol))

data %>% subset(contract_type == "2 Next Week") %>%
  subset(vol == min(vol))

data %>% subset(contract_type == "3 Current Season") %>%
  subset(vol == min(vol))

data %>% subset(contract_type == "4 Next Season") %>%
  subset(vol == min(vol))
```

